services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed fedirjh/udagram-api-feed:v1
  - docker tag udagram-api-user fedirjh/udagram-api-user:v1
  - docker tag udagram-frontend fedirjh/udagram-frontend:v1
  - docker tag reverseproxy fedirjh/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fedirjh/udagram-api-feed:v1
  - docker push fedirjh/udagram-api-user:v1
  - docker push fedirjh/udagram-frontend:v1
  - docker push fedirjh/reverseproxy:v1
