apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - image: fedirjh/udagram-api-feed:v1
          name: backend-feed
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cmap
            - configMapRef:
                name: envsecret
          ports:
            - containerPort: 8080
      restartPolicy: Always
