apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - image: fedirjh/udagram-frontend:v1
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
