apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-user
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - image: fedirjh/udagram-api-user:v1
          name: backend-user
          envFrom:
            - configMapRef:
                name: cmap
            - configMapRef:
                name: envsecret
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
